description: Steam game data
type: source
columns:
  url:
    type: STR
  types:
    type: STR
  name:
    type: STR
  desc_snippet:
    type: STR
  recent_reviews:
    type: STR
  all_reviews:
    type: STR
  release_date:
    type: STR
  developer:
    type: STR
  publisher:
    type: STR
  popular_tags:
    type: STR
  game_details:
    type: STR
  languages:
    type: STR
  achievements:
    type: STR
  genre:
    type: STR
  game_description:
    type: STR
  mature_content:
    type: STR
  minimum_requirements:
    type: STR
  recommended_requirements:
    type: STR
  original_price:
    type: STR
  discount_price:
    type: STR
tables:
  cockroachdb:
  - catalog: null
    schema: public
    table: games
    cost: 1.0
