# coding: utf-8

"""
    DJ server

    A DataJunction metrics layer  # noqa: E501

    The version of the OpenAPI document: 0.0.post1.dev1+g285ddf5
    Generated by: https://openapi-generator.tech
"""

import unittest

import djopenapi
from djopenapi.model.node_revision_base import NodeRevisionBase
from djopenapi import configuration


class TestNodeRevisionBase(unittest.TestCase):
    """NodeRevisionBase unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
