# coding: utf-8

"""
    DJ server

    A DataJunction metrics layer  # noqa: E501

    The version of the OpenAPI document: 0.0.post1.dev1+gc6563af
    Generated by: https://openapi-generator.tech
"""

import unittest

import djopenapi
from djopenapi.model.materialization_config_output import MaterializationConfigOutput
from djopenapi import configuration


class TestMaterializationConfigOutput(unittest.TestCase):
    """MaterializationConfigOutput unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
