# coding: utf-8

"""
    DJ server

    A DataJunction metrics layer  # noqa: E501

    The version of the OpenAPI document: 0.0.post1.dev1+g2d1ed5e
    Generated by: https://openapi-generator.tech
"""

import unittest

import djopenapi
from djopenapi.model.node_revision_output import NodeRevisionOutput
from djopenapi import configuration


class TestNodeRevisionOutput(unittest.TestCase):
    """NodeRevisionOutput unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
