# coding: utf-8

"""
    DJ server

    A DataJunction metrics layer  # noqa: E501

    The version of the OpenAPI document: 0.0.post1.dev1+g1e86dc4
    Generated by: https://openapi-generator.tech
"""

import unittest

import djopenapi
from djopenapi.model.cube_revision_metadata import CubeRevisionMetadata
from djopenapi import configuration


class TestCubeRevisionMetadata(unittest.TestCase):
    """CubeRevisionMetadata unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
