# coding: utf-8

"""
    DJ server

    A DataJunction metrics layer  # noqa: E501

    The version of the OpenAPI document: 0.0.post1.dev1+g9dc3258
    Generated by: https://openapi-generator.tech
"""

import unittest

import djopenapi
from djopenapi.model.source_node_column_type import SourceNodeColumnType
from djopenapi import configuration


class TestSourceNodeColumnType(unittest.TestCase):
    """SourceNodeColumnType unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
