# coding: utf-8

"""
    DJ server

    A DataJunction metrics layer  # noqa: E501

    The version of the OpenAPI document: 0.0.post1.dev1+g9dc3258
    Generated by: https://openapi-generator.tech
"""

import unittest

import djopenapi
from djopenapi.model.http_validation_error import HTTPValidationError
from djopenapi import configuration


class TestHTTPValidationError(unittest.TestCase):
    """HTTPValidationError unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
