# coding: utf-8

"""
    DJ server

    A DataJunction metrics layer  # noqa: E501

    The version of the OpenAPI document: 0.0.post1.dev1+g7537d5c
    Generated by: https://openapi-generator.tech
"""

import unittest

import djopenapi
from djopenapi.model.node_status import NodeStatus
from djopenapi import configuration


class TestNodeStatus(unittest.TestCase):
    """NodeStatus unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
