# coding: utf-8

"""
    DJ server

    A DataJunction metrics layer  # noqa: E501

    The version of the OpenAPI document: 0.0.post1.dev1+g6ea8804
    Generated by: https://openapi-generator.tech
"""

import unittest

import djopenapi
from djopenapi.model.column_attribute_input import ColumnAttributeInput
from djopenapi import configuration


class TestColumnAttributeInput(unittest.TestCase):
    """ColumnAttributeInput unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
