# coding: utf-8

"""
    DJ server

    A DataJunction metrics layer  # noqa: E501

    The version of the OpenAPI document: 0.0.post1.dev1+gd5a7903
    Generated by: https://openapi-generator.tech
"""

import unittest

import djopenapi
from djopenapi.model.tag import Tag
from djopenapi import configuration


class TestTag(unittest.TestCase):
    """Tag unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
