# coding: utf-8

"""
    DJ server

    A DataJunction metrics layer  # noqa: E501

    The version of the OpenAPI document: 0.0.post1.dev1+g6ea8804
    Generated by: https://openapi-generator.tech
"""

import unittest

import djopenapi
from djopenapi.model.attribute_type import AttributeType
from djopenapi import configuration


class TestAttributeType(unittest.TestCase):
    """AttributeType unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
