# coding: utf-8

"""
    DJ server

    A DataJunction metrics layer  # noqa: E501

    The version of the OpenAPI document: 0.0.post1.dev1+g15a6374
    Generated by: https://openapi-generator.tech
"""

import unittest

import djopenapi
from djopenapi.model.tag_output import TagOutput
from djopenapi import configuration


class TestTagOutput(unittest.TestCase):
    """TagOutput unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
