files: ^datajunction-query/
exclude: (^datajunction-query/docker/)

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: trailing-whitespace
  - id: check-ast
    exclude: templates/
  - id: check-merge-conflict
  - id: debug-statements
    exclude: templates/

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.22
  hooks:
    - id: ruff-check
      args: [ --fix ]
    - id: ruff-format

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v2.3.0'  # Use the sha / tag you want to point at
  hooks:
  - id: mypy
    exclude: templates/
    additional_dependencies:
    - types-requests
    - types-freezegun
    - types-python-dateutil
    - types-setuptools
    - types-PyYAML
    - types-tabulate
    - types-toml

- repo: https://github.com/asottile/add-trailing-comma
  rev: v4.0.0
  hooks:
  - id: add-trailing-comma
