engines:
  - name: duckdb
    version: 0.7.1
    type: duckdb
    uri: duckdb:////code/docker/default.duckdb
    extra_params:
      location: /code/docker/default.duckdb
  - name: trino
    version: 451
    type: sqlalchemy
    uri: trino://trino-coordinator:8080/tpch/sf1
    extra_params:
      http_scheme: http
      user: admin
  - name: dj_system
    version: ''
    type: sqlalchemy
    uri: postgresql+psycopg://readonly_user:readonly_pass@postgres_metadata:5432/dj
catalogs:
  - name: warehouse
    engines:
      - duckdb
  - name: tpch
    engines:
      - trino
  - name: dj
    engines:
      - dj_system
