# coding: utf-8

"""
    DJ server

    A DataJunction metrics layer  # noqa: E501

    The version of the OpenAPI document: 0.0.post1.dev1+g9dc3258
    Generated by: https://openapi-generator.tech
"""

from djopenapi.paths.attributes_.post import AddAttributeTypeAttributesPost
from djopenapi.paths.data_node_name_availability_.post import AddAvailabilityDataNodeNameAvailabilityPost
from djopenapi.paths.catalogs_.post import AddCatalogCatalogsPost
from djopenapi.paths.nodes_name_columns_column_.post import AddDimensionToNodeNodesNameColumnsColumnPost
from djopenapi.paths.engines_.post import AddEngineEnginesPost
from djopenapi.paths.catalogs_name_engines_.post import AddEnginesToCatalogCatalogsNameEnginesPost
from djopenapi.paths.nodes_name_tag_.post import AddTagToNodeNodesNameTagPost
from djopenapi.paths.metrics_common_dimensions_.get import CommonDimensionsMetricsCommonDimensionsGet
from djopenapi.paths.nodes_cube_.post import CreateCubeNodeNodesCubePost
from djopenapi.paths.nodes_dimension_.post import CreateNodeNodesDimensionPost
from djopenapi.paths.nodes_metric_.post import CreateNodeNodesMetricPost
from djopenapi.paths.nodes_transform_.post import CreateNodeNodesTransformPost
from djopenapi.paths.nodes_source_.post import CreateSourceNodeNodesSourcePost
from djopenapi.paths.tags_.post import CreateTagTagsPost
from djopenapi.paths.data_node_name_.get import DataForNodeDataNodeNameGet
from djopenapi.paths.nodes_name_downstream_.get import DownstreamNodesNodesNameDownstreamGet
from djopenapi.paths.tags_name_nodes_.get import FindNodesByTagTagsNameNodesGet
from djopenapi.paths.sql_node_name_.get import GetSqlForNodeSqlNodeNameGet
from djopenapi.paths.health_.get import HealthHealthGet
from djopenapi.paths.attributes_.get import ListAttributesAttributesGet
from djopenapi.paths.catalogs_.get import ListCatalogsCatalogsGet
from djopenapi.paths.engines_name_version_.get import ListEngineEnginesNameVersionGet
from djopenapi.paths.engines_.get import ListEnginesEnginesGet
from djopenapi.paths.nodes_name_revisions_.get import ListNodeRevisionsNodesNameRevisionsGet
from djopenapi.paths.tags_.get import ListTagsTagsGet
from djopenapi.paths.nodes_similarity_node1_name_node2_name.get import NodeSimilarityNodesSimilarityNode1NameNode2NameGet
from djopenapi.paths.catalogs_name_.get import ReadCatalogCatalogsNameGet
from djopenapi.paths.cubes_name_.get import ReadCubeCubesNameGet
from djopenapi.paths.metrics_name_.get import ReadMetricMetricsNameGet
from djopenapi.paths.metrics_.get import ReadMetricsMetricsGet
from djopenapi.paths.query_sql.get import ReadMetricsSqlQuerySqlGet
from djopenapi.paths.nodes_name_.get import ReadNodeNodesNameGet
from djopenapi.paths.nodes_.get import ReadNodesNodesGet
from djopenapi.paths.tags_name_.get import ReadTagTagsNameGet
from djopenapi.paths.nodes_node_name_attributes_.post import SetColumnAttributesNodesNodeNameAttributesPost
from djopenapi.paths.nodes_name_.patch import UpdateNodeNodesNamePatch
from djopenapi.paths.tags_name_.patch import UpdateTagTagsNamePatch
from djopenapi.paths.nodes_name_materialization_.post import UpsertNodeMaterializationConfigNodesNameMaterializationPost
from djopenapi.paths.nodes_validate_.post import ValidateNodeNodesValidatePost


class DefaultApi(
    AddAttributeTypeAttributesPost,
    AddAvailabilityDataNodeNameAvailabilityPost,
    AddCatalogCatalogsPost,
    AddDimensionToNodeNodesNameColumnsColumnPost,
    AddEngineEnginesPost,
    AddEnginesToCatalogCatalogsNameEnginesPost,
    AddTagToNodeNodesNameTagPost,
    CommonDimensionsMetricsCommonDimensionsGet,
    CreateCubeNodeNodesCubePost,
    CreateNodeNodesDimensionPost,
    CreateNodeNodesMetricPost,
    CreateNodeNodesTransformPost,
    CreateSourceNodeNodesSourcePost,
    CreateTagTagsPost,
    DataForNodeDataNodeNameGet,
    DownstreamNodesNodesNameDownstreamGet,
    FindNodesByTagTagsNameNodesGet,
    GetSqlForNodeSqlNodeNameGet,
    HealthHealthGet,
    ListAttributesAttributesGet,
    ListCatalogsCatalogsGet,
    ListEngineEnginesNameVersionGet,
    ListEnginesEnginesGet,
    ListNodeRevisionsNodesNameRevisionsGet,
    ListTagsTagsGet,
    NodeSimilarityNodesSimilarityNode1NameNode2NameGet,
    ReadCatalogCatalogsNameGet,
    ReadCubeCubesNameGet,
    ReadMetricMetricsNameGet,
    ReadMetricsMetricsGet,
    ReadMetricsSqlQuerySqlGet,
    ReadNodeNodesNameGet,
    ReadNodesNodesGet,
    ReadTagTagsNameGet,
    SetColumnAttributesNodesNodeNameAttributesPost,
    UpdateNodeNodesNamePatch,
    UpdateTagTagsNamePatch,
    UpsertNodeMaterializationConfigNodesNameMaterializationPost,
    ValidateNodeNodesValidatePost,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
