files: ^datajunction-(server|query|reflection)/
exclude: (^docs/|^openapi/|^datajunction-clients/python/|^datajunction-clients/javascript/|^datajunction-server/datajunction_server/sql/parsing/backends/grammar/generated|^README.md)

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: trailing-whitespace
  - id: check-ast
    exclude: templates/
  - id: check-merge-conflict
  - id: debug-statements
    exclude: templates/

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.22
  hooks:
    - id: ruff-check
      args: [ --fix ]
    - id: ruff-format

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v2.3.0'
  hooks:
  - id: mypy
    name: mypy (datajunction-server)
    files: ^datajunction-server/
    exclude: templates/
    args: [--ignore-missing-imports, --scripts-are-modules, --config-file=datajunction-server/pyproject.toml]
    additional_dependencies: &mypy-deps
    - types-requests
    - types-freezegun
    - types-python-dateutil
    - types-setuptools
    - types-PyYAML
    - types-tabulate
  - id: mypy
    name: mypy (datajunction-query)
    files: ^datajunction-query/
    exclude: templates/
    additional_dependencies:
    - types-requests
    - types-freezegun
    - types-python-dateutil
    - types-setuptools
    - types-PyYAML
    - types-tabulate
    - types-toml
  - id: mypy
    name: mypy (datajunction-reflection)
    files: ^datajunction-reflection/
    exclude: templates/
    additional_dependencies: *mypy-deps

- repo: https://github.com/asottile/add-trailing-comma
  rev: v4.0.0
  hooks:
  - id: add-trailing-comma

- repo: https://github.com/asottile/pyupgrade
  rev: v3.21.2
  hooks:
  - id: pyupgrade
    args: [--py310-plus]
