# WARNING: this is not a standaonle docker config file. It must be used in addition to the docker-compose.yml.
#          If in doubt please use the Makefile commands to build DJ docker containers.
version: "2.2"

volumes:
  middle_var: {}
  historical_var: {}
  broker_var: {}
  coordinator_var: {}
  router_var: {}
  druid_shared: {}

services:
  druid_postgres:
    container_name: druid_postgres
    image: postgres:latest
    volumes:
      - metadata_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=FoolishPassword
      - POSTGRES_USER=druid
      - POSTGRES_DB=druid

  # Need 3.5 or later for container nodes
  druid_zookeeper:
    container_name: druid_zookeeper
    image: zookeeper:3.5
    ports:
      - "2181:2181"
    environment:
      - ZOO_MY_ID=1

  druid_coordinator:
    image: apache/druid:0.20.0
    container_name: druid_coordinator
    volumes:
      - druid_shared:/opt/shared
      - coordinator_var:/opt/druid/var
    depends_on:
      - druid_zookeeper
      - druid_postgres
    ports:
      - "8081:8081"
    command:
      - coordinator
    env_file:
      - ./examples/docker/druid_environment

  druid_broker:
    image: apache/druid:0.20.0
    container_name: druid_broker
    volumes:
      - broker_var:/opt/druid/var
    depends_on:
      - druid_zookeeper
      - druid_postgres
      - druid_coordinator
    ports:
      - "8082:8082"
    command:
      - broker
    env_file:
      - ./examples/docker/druid_environment

  druid_historical:
    image: apache/druid:0.20.0
    container_name: druid_historical
    volumes:
      - druid_shared:/opt/shared
      - historical_var:/opt/druid/var
    depends_on:
      - druid_zookeeper
      - druid_postgres
      - druid_coordinator
    ports:
      - "8083:8083"
    command:
      - historical
    env_file:
      - ./examples/docker/druid_environment

  druid_middlemanager:
    image: apache/druid:0.20.0
    container_name: druid_middlemanager
    volumes:
      - druid_shared:/opt/shared
      - middle_var:/opt/druid/var
    depends_on:
      - druid_zookeeper
      - druid_postgres
      - druid_coordinator
    ports:
      - "8091:8091"
      - "8100-8105:8100-8105"
    command:
      - middleManager
    env_file:
      - ./examples/docker/druid_environment

  druid_router:
    image: apache/druid:0.20.0
    container_name: druid_router
    volumes:
      - router_var:/opt/druid/var
    depends_on:
      - druid_zookeeper
      - druid_postgres
      - druid_coordinator
    ports:
      - "8888:8888"
    command:
      - router
    env_file:
      - ./examples/docker/druid_environment

  druid_ingest:
    image: curlimages/curl
    depends_on:
      - druid_router
    container_name: druid_ingest
    volumes:
      - ./examples/docker/druid_init.sh:/druid_init.sh
      - ./examples/docker/druid_spec.json:/druid_spec.json
      - ./examples/docker/wait-for:/wait-for
    entrypoint: sh -c './wait-for coordinator:8081 -- /druid_init.sh'
