# coding: utf-8

"""
    DJ server

    A DataJunction metrics repository  # noqa: E501

    The version of the OpenAPI document: 0.0.post1.dev1+ge24cd2b
    Generated by: https://openapi-generator.tech
"""

import unittest

import djclient
from djclient.model.node_validation import NodeValidation
from djclient import configuration


class TestNodeValidation(unittest.TestCase):
    """NodeValidation unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
