# coding: utf-8

"""
    DJ server

    A DataJunction metrics layer  # noqa: E501

    The version of the OpenAPI document: 0.0.post1.dev1+gb6071cf
    Generated by: https://openapi-generator.tech
"""

import unittest

import djclient
from djclient.model.create_table import CreateTable
from djclient import configuration


class TestCreateTable(unittest.TestCase):
    """CreateTable unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
