# coding: utf-8

"""
    DJ server

    A DataJunction metrics layer  # noqa: E501

    The version of the OpenAPI document: 0.0.post1.dev1+g9649557
    Generated by: https://openapi-generator.tech
"""

import unittest

import djclient
from djclient.model.upsert_materialization_config import UpsertMaterializationConfig
from djclient import configuration


class TestUpsertMaterializationConfig(unittest.TestCase):
    """UpsertMaterializationConfig unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
