# coding: utf-8

"""
    DJ server

    A DataJunction metrics repository  # noqa: E501

    The version of the OpenAPI document: 0.0.post1.dev1+g8793b6c
    Generated by: https://openapi-generator.tech
"""

import unittest

import djclient
from djclient.model.source_node_column_type import SourceNodeColumnType
from djclient import configuration


class TestSourceNodeColumnType(unittest.TestCase):
    """SourceNodeColumnType unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
