# coding: utf-8

"""
    DJ server

    A DataJunction metrics layer  # noqa: E501

    The version of the OpenAPI document: 0.0.post1.dev1+gd8cb070
    Generated by: https://openapi-generator.tech
"""

import unittest

import djclient
from djclient.model.simple_column import SimpleColumn
from djclient import configuration


class TestSimpleColumn(unittest.TestCase):
    """SimpleColumn unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
