# coding: utf-8

"""
    DJ server

    A DataJunction metrics repository  # noqa: E501

    The version of the OpenAPI document: 0.0.post1.dev1+g9c5d385
    Generated by: https://openapi-generator.tech
"""

import unittest

import djclient
from djclient.model.create_column import CreateColumn
from djclient import configuration


class TestCreateColumn(unittest.TestCase):
    """CreateColumn unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
