# coding: utf-8

"""
    DJ server

    A DataJunction metrics layer  # noqa: E501

    The version of the OpenAPI document: 0.0.post1.dev1+g2c9eaae
    Generated by: https://openapi-generator.tech
"""

import unittest

import djclient
from djclient.model.node_mode import NodeMode
from djclient import configuration


class TestNodeMode(unittest.TestCase):
    """NodeMode unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
