# coding: utf-8

"""
    DJ server

    A DataJunction metrics layer  # noqa: E501

    The version of the OpenAPI document: 0.0.post1.dev1+g4e49348
    Generated by: https://openapi-generator.tech
"""

import unittest

import djclient
from djclient.model.node_revision_base import NodeRevisionBase
from djclient import configuration


class TestNodeRevisionBase(unittest.TestCase):
    """NodeRevisionBase unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
