# coding: utf-8

"""
    DJ server

    A DataJunction metrics layer  # noqa: E501

    The version of the OpenAPI document: 0.0.post1.dev1+g0f458e3
    Generated by: https://openapi-generator.tech
"""

import unittest

import djclient
from djclient.model.healthcheck_status import HealthcheckStatus
from djclient import configuration


class TestHealthcheckStatus(unittest.TestCase):
    """HealthcheckStatus unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
