# coding: utf-8

"""
    DJ server

    A DataJunction metrics layer  # noqa: E501

    The version of the OpenAPI document: 0.0.post1.dev1+gb0fe2cb
    Generated by: https://openapi-generator.tech
"""

import unittest

import djclient
from djclient.model.attribute_type_name import AttributeTypeName
from djclient import configuration


class TestAttributeTypeName(unittest.TestCase):
    """AttributeTypeName unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
