# coding: utf-8

"""
    DJ server

    A DataJunction metrics layer  # noqa: E501

    The version of the OpenAPI document: 0.0.post1.dev1+g5d0aa56
    Generated by: https://openapi-generator.tech
"""

import unittest

import djclient
from djclient.model.attribute_output import AttributeOutput
from djclient import configuration


class TestAttributeOutput(unittest.TestCase):
    """AttributeOutput unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
