# coding: utf-8

"""
    DJ server

    A DataJunction metrics layer  # noqa: E501

    The version of the OpenAPI document: 0.0.post1.dev1+gcbe8893
    Generated by: https://openapi-generator.tech
"""

import unittest

import djclient
from djclient.model.create_source_node import CreateSourceNode
from djclient import configuration


class TestCreateSourceNode(unittest.TestCase):
    """CreateSourceNode unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
