# coding: utf-8

"""
    DJ server

    A DataJunction metrics repository  # noqa: E501

    The version of the OpenAPI document: 0.0.post1.dev1+g404b1f9
    Generated by: https://openapi-generator.tech
"""

import unittest

import djclient
from djclient.model.update_node import UpdateNode
from djclient import configuration


class TestUpdateNode(unittest.TestCase):
    """UpdateNode unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
