# coding: utf-8

"""
    DJ server

    A DataJunction metrics layer  # noqa: E501

    The version of the OpenAPI document: 0.0.post1.dev1+ge24d408
    Generated by: https://openapi-generator.tech
"""

import unittest

import djclient
from djclient.model.update_tag import UpdateTag
from djclient import configuration


class TestUpdateTag(unittest.TestCase):
    """UpdateTag unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
