# coding: utf-8

"""
    DJ server

    A DataJunction metrics layer  # noqa: E501

    The version of the OpenAPI document: 0.0.post1.dev1+g9dc3258
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from djopenapi import schemas  # noqa: F401


class NodeType(
    schemas.EnumBase,
    schemas.StrSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Node type.

A node can have 4 types, currently:

1. SOURCE nodes are root nodes in the DAG, and point to tables or views in a DB.
2. TRANSFORM nodes are SQL transformations, reading from SOURCE/TRANSFORM nodes.
3. METRIC nodes are leaves in the DAG, and have a single aggregation query.
4. DIMENSION nodes are special SOURCE nodes that can be auto-joined with METRICS.
5. CUBE nodes contain a reference to a set of METRICS and a set of DIMENSIONS.
    """


    class MetaOapg:
        enum_value_to_name = {
            "source": "SOURCE",
            "transform": "TRANSFORM",
            "metric": "METRIC",
            "dimension": "DIMENSION",
            "cube": "CUBE",
        }
    
    @schemas.classproperty
    def SOURCE(cls):
        return cls("source")
    
    @schemas.classproperty
    def TRANSFORM(cls):
        return cls("transform")
    
    @schemas.classproperty
    def METRIC(cls):
        return cls("metric")
    
    @schemas.classproperty
    def DIMENSION(cls):
        return cls("dimension")
    
    @schemas.classproperty
    def CUBE(cls):
        return cls("cube")
