// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'queryBuilder': string;
  'ruleGroup': string;
  'svg-font-color': string;
}
export const cssExports: CssExports;
export default cssExports;
