description: Country level agg table
type: transform
query: |-
  SELECT "dbt.source.jaffle_shop.customers".id,
         "dbt.source.jaffle_shop.customers".first_name,
         "dbt.source.jaffle_shop.customers".last_name,
         COUNT(1) AS order_cnt
  FROM dbt.source.jaffle_shop.orders o
  JOIN dbt.source.jaffle_shop.customers c ON o.user_id = c.id
  GROUP BY "dbt.source.jaffle_shop.customers".id,
           "dbt.source.jaffle_shop.customers".first_name,
           "dbt.source.jaffle_shop.customers".last_name
columns:
  id:
    type: INT
  first_name:
    type: STR
  last_name:
    type: STR
  order_cnt:
    type: INT
