"""Add version field to History table.

Revision ID: 5a8eb7b2a9c6
Revises: ee0eb65f743b
Create Date: 2025-06-02 22:41:19.560144+00:00

"""
# pylint: disable=no-member, invalid-name, missing-function-docstring, unused-import, no-name-in-module

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "5a8eb7b2a9c6"
down_revision = "ee0eb65f743b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("history", schema=None) as batch_op:
        batch_op.add_column(sa.Column("version", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("history", schema=None) as batch_op:
        batch_op.drop_column("version")

    # ### end Alembic commands ###
