name: Update and Commit OpenAPI Spec
on: [workflow_dispatch]
jobs:
  update-openapi-spec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install DJ
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Generate OpenAPI Spec
        run: ./scripts/generate-openapi.py -o openapi.json

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Get Today's Date
        id: date
        run: echo "::set-output name=date::$(date +'%m-%d-%Y')"

      - name: Commit OpenAPI Spec & Push to ci-pr/openapi Branch
        run: |
          git add openapi.json
          git commit -m "Adding updated OpenAPI Spec"
          git checkout -b ci-pr/openapi-${{ steps.date.outputs.date }}
          git push --set-upstream origin ci-pr/openapi-${{ steps.date.outputs.date }}

      - name: Open a PR (ci-pr/openapi -> main)
        run: gh pr create -B main -H ci-pr/openapi-${{ steps.date.outputs.date }} --title 'Update OpenAPI Spec - ${{ steps.date.outputs.date }}' --body '(This PR was generated by a GitHub action)'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
