"""store query ast

Revision ID: 46ab14aad347
Revises: ab36a0560a57
Create Date: 2023-08-18 05:29:58.034161+00:00

"""
# pylint: disable=no-member, invalid-name, missing-function-docstring, unused-import, no-name-in-module

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision = '46ab14aad347'
down_revision = 'ab36a0560a57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('noderevision', sa.Column('ast_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('noderevision', 'ast_id')
    # ### end Alembic commands ###
