"""add bound_dimensions attribute to NodeRevision

Revision ID: 25637bbf2d52
Revises: bd313a10e2a8
Create Date: 2023-07-12 00:08:36.837033+00:00

"""
# pylint: disable=no-member, invalid-name, missing-function-docstring, unused-import, no-name-in-module

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision = '25637bbf2d52'
down_revision = 'bd313a10e2a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
