"""Add partitions

Revision ID: 7b265a3be837
Revises: 58e246fba34b
Create Date: 2023-10-11 03:19:37.595305+00:00

"""
# pylint: disable=no-member, invalid-name, missing-function-docstring, unused-import, no-name-in-module

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision = '7b265a3be837'
down_revision = '58e246fba34b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('granularity', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('format', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.drop_column('expression')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expression', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('format')
        batch_op.drop_column('granularity')

    # ### end Alembic commands ###
