description: Country level agg table
type: transform
query: |-
  SELECT country,
         COUNT(DISTINCT id) AS num_users
  FROM basic.source.users
  GROUP BY 1
columns:
  country:
    type: STR
  num_users:
    type: INT
