[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pdm.build]
includes = ["dj"]

[project]
name = "datajunction-server"
dynamic = ["version"]
description = "DataJunction server library for running to a DataJunction server"
authors = [
    {name = "DataJunction Authors", email = "yian.shang@gmail.com"},
]
dependencies = [
    "alembic>=1.10.3",
    "SQLAlchemy-Utils<1.0.0,>=0.40.0",
    "accept-types<1.0.0,>=0.4.1",
    "antlr4-python3-runtime==4.12.0",
    "asciidag<1.0.0,>=0.2.0",
    "cachelib<1.0.0,>=0.10.2",
    "celery<6.0.0,>=5.2.7",
    "google-api-python-client>=2.95.0",
    "google-auth-httplib2>=0.1.0",
    "google-auth-oauthlib>=1.0.0",
    "fastapi<0.80.0,>=0.79.0",
    "msgpack<2.0.0,>=1.0.5",
    "opentelemetry-instrumentation-fastapi==0.38b0",
    "python-dotenv<1.0.0,>=0.19.0",
    "redis<5.0.0,>=4.5.4",
    "requests<=2.29.0,>=2.28.2",
    "rich<14.0.0,>=13.3.3",
    "SQLAlchemy<2.0.0,>=1.4.41",
    "sqlmodel<1.0.0,>=0.0.8",
    "sqlparse<1.0.0,>=0.4.3",
    "sse-starlette>=1.6.0",
    "yarl<2.0.0,>=1.8.2",
    "python-multipart>=0.0.6",
    "passlib>=1.7.4",
    "python-jose>=3.3.0",
    "cryptography>=41.0.3",
    "bcrypt>=4.0.1",
    "line-profiler>=4.0.3",
    "cachetools>=5.3.1",
    "types-cachetools>=5.3.0.6",
    "strawberry-graphql>=0.204.0",
]
requires-python = ">=3.8,<4.0"
readme = "README.md"
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]

[project.optional-dependencies]
uvicorn = [
    "uvicorn[standard]>=0.21.1",
]
transpilation = [
    "sqlglot>=18.0.1",
]

[project.entry-points.'superset.db_engine_specs']
dj = 'datajunction_server.superset:DJEngineSpec'

[tool.hatch.version]
path = "datajunction_server/__about__.py"

[project.urls]
repository = "https://github.com/DataJunction/dj"

[tool.pdm.dev-dependencies]
test = [
    "codespell>=2.2.4",
    "freezegun>=1.2.2",
    "pre-commit>=3.2.2",
    "pylint>=2.17.3",
    "pytest-asyncio>=0.15.1",
    "pytest-cov>=4.0.0",
    "pytest-integration>=0.2.2",
    "pytest-mock>=3.10.0",
    "pytest>=7.3.0",
    "requests-mock>=1.10.0",
    "typing-extensions>=4.5.0",
    "pytest-xdist>=3.3.0",
    "duckdb==0.8.1",
]

[[tool.pdm.autoexport]]
filename = "requirements/docker.txt"
groups = ["default", "uvicorn", "transpilation"]
without-hashes = true

[[tool.pdm.autoexport]]
filename = "requirements/test.txt"
groups = ["default", "test"]
without-hashes = true

[tool.coverage.run]
source = ['datajunction_server/']

[tool.isort]
src_paths = ["datajunction_server/", "tests/"]
profile = 'black'
