"""
fixtures for tpcds_q99.sql
"""


import pytest

from dj.sql.parsing.ast import (
    Alias,
    Between,
    BinaryOp,
    BinaryOpKind,
    Case,
    Column,
    From,
    Function,
    Identifier,
    Name,
    Number,
    Query,
    Select,
    Table,
    UnaryOp,
    UnaryOpKind,
)


@pytest.fixture
def tpcds_q99():
    """
    dj ast for tpcds query 99
    """
    return Query(
        select=Select(
            distinct=False,
            from_=From(
                table=Table(
                    ident=Identifier(
                        idents=[Name(name="catalog_sales", quote_style="")],
                    ),
                ),
                joins=[],
            ),
            group_by=[
                Function(
                    ident=Identifier(idents=[Name(name="Substr", quote_style="")]),
                    args=[
                        Column(
                            ident=Identifier(
                                idents=[Name(name="w_warehouse_name", quote_style="")],
                            ),
                        ),
                        Number(value=1),
                        Number(value=20),
                    ],
                ),
                Column(ident=Identifier(idents=[Name(name="sm_type", quote_style="")])),
                Column(ident=Identifier(idents=[Name(name="cc_name", quote_style="")])),
            ],
            having=BinaryOp(
                left=BinaryOp(
                    left=BinaryOp(
                        left=BinaryOp(
                            left=UnaryOp(
                                op=UnaryOpKind.Not,
                                expr=Between(
                                    expr=Column(
                                        ident=Identifier(
                                            idents=[
                                                Name(
                                                    name="d_month_seq",
                                                    quote_style="",
                                                ),
                                            ],
                                        ),
                                    ),
                                    low=UnaryOp(
                                        op=UnaryOpKind.Plus,
                                        expr=Number(value=1200),
                                    ),
                                    high=BinaryOp(
                                        left=Number(value=1200),
                                        op=BinaryOpKind.Plus,
                                        right=Number(value=11),
                                    ),
                                ),
                            ),
                            op=BinaryOpKind.And,
                            right=BinaryOp(
                                left=Column(
                                    ident=Identifier(
                                        idents=[
                                            Name(
                                                name="cs_ship_date_sk",
                                                quote_style="",
                                            ),
                                        ],
                                    ),
                                ),
                                op=BinaryOpKind.Eq,
                                right=Column(
                                    ident=Identifier(
                                        idents=[Name(name="d_date_sk", quote_style="")],
                                    ),
                                ),
                            ),
                        ),
                        op=BinaryOpKind.And,
                        right=BinaryOp(
                            left=Column(
                                ident=Identifier(
                                    idents=[
                                        Name(name="cs_warehouse_sk", quote_style=""),
                                    ],
                                ),
                            ),
                            op=BinaryOpKind.Eq,
                            right=Column(
                                ident=Identifier(
                                    idents=[
                                        Name(name="w_warehouse_sk", quote_style=""),
                                    ],
                                ),
                            ),
                        ),
                    ),
                    op=BinaryOpKind.And,
                    right=BinaryOp(
                        left=Column(
                            ident=Identifier(
                                idents=[Name(name="cs_ship_mode_sk", quote_style="")],
                            ),
                        ),
                        op=BinaryOpKind.Eq,
                        right=Column(
                            ident=Identifier(
                                idents=[Name(name="sm_ship_mode_sk", quote_style="")],
                            ),
                        ),
                    ),
                ),
                op=BinaryOpKind.And,
                right=BinaryOp(
                    left=Column(
                        ident=Identifier(
                            idents=[Name(name="cs_call_center_sk", quote_style="")],
                        ),
                    ),
                    op=BinaryOpKind.Eq,
                    right=Column(
                        ident=Identifier(
                            idents=[Name(name="cc_call_center_sk", quote_style="")],
                        ),
                    ),
                ),
            ),
            projection=[
                Function(
                    ident=Identifier(idents=[Name(name="Substr", quote_style="")]),
                    args=[
                        Column(
                            ident=Identifier(
                                idents=[Name(name="w_warehouse_name", quote_style="")],
                            ),
                        ),
                        Number(value=1),
                        Number(value=20),
                    ],
                ),
                Column(ident=Identifier(idents=[Name(name="sm_type", quote_style="")])),
                Column(ident=Identifier(idents=[Name(name="cc_name", quote_style="")])),
                Alias(
                    ident=Identifier(idents=[Name(name="30 days", quote_style="'")]),
                    child=Function(
                        ident=Identifier(idents=[Name(name="Sum", quote_style="")]),
                        args=[
                            Case(
                                conditions=[
                                    BinaryOp(
                                        left=BinaryOp(
                                            left=Column(
                                                ident=Identifier(
                                                    idents=[
                                                        Name(
                                                            name="cs_ship_date_sk",
                                                            quote_style="",
                                                        ),
                                                    ],
                                                ),
                                            ),
                                            op=BinaryOpKind.Minus,
                                            right=Column(
                                                ident=Identifier(
                                                    idents=[
                                                        Name(
                                                            name="cs_sold_date_sk",
                                                            quote_style="",
                                                        ),
                                                    ],
                                                ),
                                            ),
                                        ),
                                        op=BinaryOpKind.LtEq,
                                        right=Number(value=30),
                                    ),
                                ],
                                else_result=Number(value=0),
                                operand=None,
                                results=[Number(value=1)],
                            ),
                        ],
                    ),
                ),
                Alias(
                    ident=Identifier(idents=[Name(name="31-60 days", quote_style="'")]),
                    child=Function(
                        ident=Identifier(idents=[Name(name="Sum", quote_style="")]),
                        args=[
                            Case(
                                conditions=[
                                    BinaryOp(
                                        left=BinaryOp(
                                            left=BinaryOp(
                                                left=Column(
                                                    ident=Identifier(
                                                        idents=[
                                                            Name(
                                                                name="cs_ship_date_sk",
                                                                quote_style="",
                                                            ),
                                                        ],
                                                    ),
                                                ),
                                                op=BinaryOpKind.Minus,
                                                right=Column(
                                                    ident=Identifier(
                                                        idents=[
                                                            Name(
                                                                name="cs_sold_date_sk",
                                                                quote_style="",
                                                            ),
                                                        ],
                                                    ),
                                                ),
                                            ),
                                            op=BinaryOpKind.Gt,
                                            right=Number(value=30),
                                        ),
                                        op=BinaryOpKind.And,
                                        right=BinaryOp(
                                            left=BinaryOp(
                                                left=Column(
                                                    ident=Identifier(
                                                        idents=[
                                                            Name(
                                                                name="cs_ship_date_sk",
                                                                quote_style="",
                                                            ),
                                                        ],
                                                    ),
                                                ),
                                                op=BinaryOpKind.Minus,
                                                right=Column(
                                                    ident=Identifier(
                                                        idents=[
                                                            Name(
                                                                name="cs_sold_date_sk",
                                                                quote_style="",
                                                            ),
                                                        ],
                                                    ),
                                                ),
                                            ),
                                            op=BinaryOpKind.LtEq,
                                            right=Number(value=60),
                                        ),
                                    ),
                                ],
                                else_result=Number(value=0),
                                operand=None,
                                results=[Number(value=1)],
                            ),
                        ],
                    ),
                ),
                Alias(
                    ident=Identifier(idents=[Name(name="61-90 days", quote_style="'")]),
                    child=Function(
                        ident=Identifier(idents=[Name(name="Sum", quote_style="")]),
                        args=[
                            Case(
                                conditions=[
                                    BinaryOp(
                                        left=BinaryOp(
                                            left=BinaryOp(
                                                left=Column(
                                                    ident=Identifier(
                                                        idents=[
                                                            Name(
                                                                name="cs_ship_date_sk",
                                                                quote_style="",
                                                            ),
                                                        ],
                                                    ),
                                                ),
                                                op=BinaryOpKind.Minus,
                                                right=Column(
                                                    ident=Identifier(
                                                        idents=[
                                                            Name(
                                                                name="cs_sold_date_sk",
                                                                quote_style="",
                                                            ),
                                                        ],
                                                    ),
                                                ),
                                            ),
                                            op=BinaryOpKind.Gt,
                                            right=Number(value=60),
                                        ),
                                        op=BinaryOpKind.And,
                                        right=BinaryOp(
                                            left=BinaryOp(
                                                left=Column(
                                                    ident=Identifier(
                                                        idents=[
                                                            Name(
                                                                name="cs_ship_date_sk",
                                                                quote_style="",
                                                            ),
                                                        ],
                                                    ),
                                                ),
                                                op=BinaryOpKind.Minus,
                                                right=Column(
                                                    ident=Identifier(
                                                        idents=[
                                                            Name(
                                                                name="cs_sold_date_sk",
                                                                quote_style="",
                                                            ),
                                                        ],
                                                    ),
                                                ),
                                            ),
                                            op=BinaryOpKind.LtEq,
                                            right=Number(value=90),
                                        ),
                                    ),
                                ],
                                else_result=Number(value=0),
                                operand=None,
                                results=[Number(value=1)],
                            ),
                        ],
                    ),
                ),
                Alias(
                    ident=Identifier(
                        idents=[Name(name="91-120 days", quote_style="'")],
                    ),
                    child=Function(
                        ident=Identifier(idents=[Name(name="Sum", quote_style="")]),
                        args=[
                            Case(
                                conditions=[
                                    BinaryOp(
                                        left=BinaryOp(
                                            left=BinaryOp(
                                                left=Column(
                                                    ident=Identifier(
                                                        idents=[
                                                            Name(
                                                                name="cs_ship_date_sk",
                                                                quote_style="",
                                                            ),
                                                        ],
                                                    ),
                                                ),
                                                op=BinaryOpKind.Minus,
                                                right=Column(
                                                    ident=Identifier(
                                                        idents=[
                                                            Name(
                                                                name="cs_sold_date_sk",
                                                                quote_style="",
                                                            ),
                                                        ],
                                                    ),
                                                ),
                                            ),
                                            op=BinaryOpKind.Gt,
                                            right=Number(value=90),
                                        ),
                                        op=BinaryOpKind.And,
                                        right=BinaryOp(
                                            left=BinaryOp(
                                                left=Column(
                                                    ident=Identifier(
                                                        idents=[
                                                            Name(
                                                                name="cs_ship_date_sk",
                                                                quote_style="",
                                                            ),
                                                        ],
                                                    ),
                                                ),
                                                op=BinaryOpKind.Minus,
                                                right=Column(
                                                    ident=Identifier(
                                                        idents=[
                                                            Name(
                                                                name="cs_sold_date_sk",
                                                                quote_style="",
                                                            ),
                                                        ],
                                                    ),
                                                ),
                                            ),
                                            op=BinaryOpKind.LtEq,
                                            right=Number(value=120),
                                        ),
                                    ),
                                ],
                                else_result=Number(value=0),
                                operand=None,
                                results=[Number(value=1)],
                            ),
                        ],
                    ),
                ),
                Alias(
                    ident=Identifier(idents=[Name(name=">120 days", quote_style="'")]),
                    child=Function(
                        ident=Identifier(idents=[Name(name="Sum", quote_style="")]),
                        args=[
                            Case(
                                conditions=[
                                    BinaryOp(
                                        left=BinaryOp(
                                            left=Column(
                                                ident=Identifier(
                                                    idents=[
                                                        Name(
                                                            name="cs_ship_date_sk",
                                                            quote_style="",
                                                        ),
                                                    ],
                                                ),
                                            ),
                                            op=BinaryOpKind.Minus,
                                            right=Column(
                                                ident=Identifier(
                                                    idents=[
                                                        Name(
                                                            name="cs_sold_date_sk",
                                                            quote_style="",
                                                        ),
                                                    ],
                                                ),
                                            ),
                                        ),
                                        op=BinaryOpKind.Gt,
                                        right=Number(value=120),
                                    ),
                                ],
                                else_result=Number(value=0),
                                operand=None,
                                results=[Number(value=1)],
                            ),
                        ],
                    ),
                ),
            ],
            where=BinaryOp(
                left=BinaryOp(
                    left=BinaryOp(
                        left=BinaryOp(
                            left=UnaryOp(
                                op=UnaryOpKind.Not,
                                expr=Between(
                                    expr=Column(
                                        ident=Identifier(
                                            idents=[
                                                Name(
                                                    name="d_month_seq",
                                                    quote_style="",
                                                ),
                                            ],
                                        ),
                                    ),
                                    low=UnaryOp(
                                        op=UnaryOpKind.Plus,
                                        expr=Number(value=1200),
                                    ),
                                    high=BinaryOp(
                                        left=Number(value=1200),
                                        op=BinaryOpKind.Plus,
                                        right=Number(value=11),
                                    ),
                                ),
                            ),
                            op=BinaryOpKind.And,
                            right=BinaryOp(
                                left=Column(
                                    ident=Identifier(
                                        idents=[
                                            Name(
                                                name="cs_ship_date_sk",
                                                quote_style="",
                                            ),
                                        ],
                                    ),
                                ),
                                op=BinaryOpKind.Eq,
                                right=Column(
                                    ident=Identifier(
                                        idents=[Name(name="d_date_sk", quote_style="")],
                                    ),
                                ),
                            ),
                        ),
                        op=BinaryOpKind.And,
                        right=BinaryOp(
                            left=Column(
                                ident=Identifier(
                                    idents=[
                                        Name(name="cs_warehouse_sk", quote_style=""),
                                    ],
                                ),
                            ),
                            op=BinaryOpKind.Eq,
                            right=Column(
                                ident=Identifier(
                                    idents=[
                                        Name(name="w_warehouse_sk", quote_style=""),
                                    ],
                                ),
                            ),
                        ),
                    ),
                    op=BinaryOpKind.And,
                    right=BinaryOp(
                        left=Column(
                            ident=Identifier(
                                idents=[Name(name="cs_ship_mode_sk", quote_style="")],
                            ),
                        ),
                        op=BinaryOpKind.Eq,
                        right=Column(
                            ident=Identifier(
                                idents=[Name(name="sm_ship_mode_sk", quote_style="")],
                            ),
                        ),
                    ),
                ),
                op=BinaryOpKind.And,
                right=BinaryOp(
                    left=Column(
                        ident=Identifier(
                            idents=[Name(name="cs_call_center_sk", quote_style="")],
                        ),
                    ),
                    op=BinaryOpKind.Eq,
                    right=Column(
                        ident=Identifier(
                            idents=[Name(name="cc_call_center_sk", quote_style="")],
                        ),
                    ),
                ),
            ),
            limit=Number(value=100),
        ),
        ctes=[],
    ).compile_parents()
