"""
fixtures for tpcds_q01.sql
"""


import pytest

from dj.sql.parsing.ast import (
    Alias,
    BinaryOp,
    BinaryOpKind,
    Column,
    From,
    Function,
    Join,
    JoinKind,
    Number,
    Query,
    Select,
    String,
    Table,
)


@pytest.fixture
def tpcds_q01():
    """
    dj ast for tpcds query 1
    """
    return Query(
        ctes=[
            Alias(
                name="customer_total_return",
                child=Select(
                    distinct=False,
                    from_=From(
                        table=Table(
                            name="store_returns",
                        ),
                        joins=[
                            Join(
                                kind=JoinKind.Inner,
                                table=Table(
                                    name="date_dim",
                                ),
                                on=BinaryOp(
                                    left=Column(
                                        name="sr_customer_sk",
                                        _table=Table(
                                            "store_returns",
                                        ),
                                    ),
                                    op=BinaryOpKind.Eq,
                                    right=Column(
                                        name="d_date_sk",
                                        _table=Table(
                                            "date_dim",
                                        ),
                                    ),
                                ),
                            ),
                        ],
                    ),
                    group_by=[
                        Column(
                            name="sr_customer_sk",
                        ),
                        Column(
                            name="sr_store_sk",
                        ),
                    ],
                    projection=[
                        Alias(
                            name="ctr_customer_sk",
                            child=Column(
                                name="sr_customer_sk",
                            ),
                        ),
                        Alias(
                            name="ctr_store_sk",
                            child=Column(
                                name="sr_store_sk",
                            ),
                        ),
                        Alias(
                            name="ctr_total_return",
                            child=Function(
                                name="Sum",
                                args=[
                                    Column(
                                        name="sr_return_amt",
                                    ),
                                ],
                            ),
                        ),
                    ],
                    where=BinaryOp(
                        left=BinaryOp(
                            left=Column(
                                name="sr_returned_date_sk",
                            ),
                            op=BinaryOpKind.Eq,
                            right=Column(
                                name="d_date_sk",
                            ),
                        ),
                        op=BinaryOpKind.And,
                        right=BinaryOp(
                            left=Column(
                                name="d_year",
                            ),
                            op=BinaryOpKind.Eq,
                            right=Number(value=2001),
                        ),
                    ),
                ),
            ),
        ],
        select=Select(
            distinct=False,
            from_=From(
                table=Alias(
                    name="ctr1",
                    child=Table(
                        name="customer_total_return",
                    ),
                ),
                joins=[
                    Join(
                        kind=JoinKind.Inner,
                        table=Table(
                            name="store",
                        ),
                        on=BinaryOp(
                            left=BinaryOp(
                                left=BinaryOp(
                                    left=Column(
                                        name="s_store_sk",
                                    ),
                                    op=BinaryOpKind.Eq,
                                    right=Column(
                                        name="ctr_store_sk",
                                        _table=Table(
                                            "ctr1",
                                        ),
                                    ),
                                ),
                                op=BinaryOpKind.And,
                                right=BinaryOp(
                                    left=Column(
                                        name="s_state",
                                    ),
                                    op=BinaryOpKind.Eq,
                                    right=String(value="TN"),
                                ),
                            ),
                            op=BinaryOpKind.And,
                            right=BinaryOp(
                                left=Column(
                                    name="ctr_customer_sk",
                                    _table=Table(
                                        "ctr1",
                                    ),
                                ),
                                op=BinaryOpKind.Eq,
                                right=Column(
                                    name="c_customer_sk",
                                ),
                            ),
                        ),
                    ),
                    Join(
                        kind=JoinKind.LeftOuter,
                        table=Table(
                            name="customer",
                        ),
                        on=BinaryOp(
                            left=BinaryOp(
                                left=BinaryOp(
                                    left=Column(
                                        name="s_store_sk",
                                    ),
                                    op=BinaryOpKind.Eq,
                                    right=Column(
                                        name="ctr_store_sk",
                                        _table=Table(
                                            "ctr1",
                                        ),
                                    ),
                                ),
                                op=BinaryOpKind.And,
                                right=BinaryOp(
                                    left=Column(
                                        name="s_state",
                                    ),
                                    op=BinaryOpKind.Eq,
                                    right=String(value="TN"),
                                ),
                            ),
                            op=BinaryOpKind.And,
                            right=BinaryOp(
                                left=Column(
                                    name="ctr_customer_sk",
                                    _table=Table(
                                        "ctr1",
                                    ),
                                ),
                                op=BinaryOpKind.Eq,
                                right=Column(
                                    name="c_customer_sk",
                                ),
                            ),
                        ),
                    ),
                ],
            ),
            projection=[
                Column(
                    name="c_customer_id",
                ),
            ],
            where=BinaryOp(
                left=BinaryOp(
                    left=BinaryOp(
                        left=Column(
                            name="ctr_total_return",
                            _table=Table(
                                "ctr1",
                            ),
                        ),
                        op=BinaryOpKind.Gt,
                        right=Query(
                            ctes=[],
                            select=Select(
                                distinct=True,
                                from_=From(
                                    table=Alias(
                                        name="ctr2",
                                        child=Table(
                                            name="customer_total_return",
                                        ),
                                    ),
                                ),
                                projection=[
                                    BinaryOp(
                                        left=Function(
                                            name="Avg",
                                            args=[
                                                Column(
                                                    name="ctr_total_return",
                                                ),
                                            ],
                                        ),
                                        op=BinaryOpKind.Multiply,
                                        right=Number(value=1.2),
                                    ),
                                ],
                                where=BinaryOp(
                                    left=Column(
                                        name="ctr_store_sk",
                                        _table=Table(
                                            "ctr1",
                                        ),
                                    ),
                                    op=BinaryOpKind.Eq,
                                    right=Column(
                                        name="ctr_store_sk",
                                        _table=Table(
                                            "ctr2",
                                        ),
                                    ),
                                ),
                                limit=None,
                            ),
                        ),
                    ),
                    op=BinaryOpKind.And,
                    right=BinaryOp(
                        left=Column(
                            name="s_store_sk",
                        ),
                        op=BinaryOpKind.Eq,
                        right=Column(
                            name="ctr_store_sk",
                            _table=Table(
                                "ctr1",
                            ),
                        ),
                    ),
                ),
                op=BinaryOpKind.Or,
                right=BinaryOp(
                    left=BinaryOp(
                        left=Column(
                            name="s_state",
                        ),
                        op=BinaryOpKind.NotEq,
                        right=String(value="TN"),
                    ),
                    op=BinaryOpKind.And,
                    right=BinaryOp(
                        left=Column(
                            name="ctr_customer_sk",
                            _table=Table(
                                "ctr1",
                            ),
                        ),
                        op=BinaryOpKind.Eq,
                        right=Column(
                            name="c_customer_sk",
                        ),
                    ),
                ),
            ),
            limit=Number(value=100),
        ),
    )
