description: Country dimension
type: dimension
query: |-
  SELECT country,
         COUNT(1) AS user_cnt
  FROM basic.dimension.users
  GROUP BY country
columns:
  country:
    type: STR
  user_cnt:
    type: INT
