# Generated by ariadne-codegen
# Source: datajunction_server/api/graphql/schema.graphql

from typing import List, Optional

from .base_model import BaseModel


class CubeDefinition(BaseModel):
    cube: Optional[str] = None
    metrics: Optional[List[str]] = None
    dimensions: Optional[List[str]] = None
    filters: Optional[List[str]] = None
    orderby: Optional[List[str]] = None


class EngineSettings(BaseModel):
    name: str
    version: Optional[str] = None
