name: Bump versions of all DJ Services and Clients.
on:
  schedule:
    - cron: "0 0 * * MON"
  workflow_dispatch:
    inputs:
      bump:
        type: choice
        description: "Hatch version option (default: alpha)"
        required: true
        default: alpha
        options:
          - major
          - minor
          - patch
          - alpha

jobs:
  publish:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']
    runs-on: 'ubuntu-latest'
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Hatch
        run: |
          python -m pip install --upgrade pip
          pip install hatch

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Bump versions
        run: |
          echo "Bump DJ Server version ..."
          pushd ./datajunction-server
          hatch version ${{ github.event.inputs.bump }}
          export NEW_VERSION=v$(hatch version)

          echo "Copy version to DJ Query Service ..."
          cp ./datajunction_server/__about__.py ../datajunction-query/djqs/

          echo "Apply to DJ Python Client ..."
          cp ./datajunction_server/__about__.py ../datajunction-clients/python/datajunction/

          echo "Apply to DJ UI Service ..."
          popd
          pushd ./datajunction-ui
          yarn version --new-version $NEW_VERSION --no-git-tag-version

      - name: Update docs (for major, minor or patch release)
        if: ${{github.event.inputs.bump == 'major' || github.event.inputs.bump == 'minor' || github.event.inputs.bump == 'patch'}}
        run: |
          echo "Releasing matching docs version ..."
          pushd ./datajunction-server
          export NEW_VERSION=v$(hatch version)
          popd
          pushd ./docs
          ./build-docs.sh $NEW_VERSION true
  
      - name: Open a PR
        run: |
          # Read the new version
          pushd ./datajunction-server
          export NEW_VERSION=v$(hatch version)
          popd

          echo "Make a PR ..."
          git add ./datajunction-*/**/__about__.py
          git add ./datajunction-ui/package.json
          git add ./docs
          git commit -m "Bumping DJ to version $NEW_VERSION ."
          git checkout -b releases/version-$NEW_VERSION
          git push --set-upstream origin releases/version-$NEW_VERSION -f

          echo "Make a tag ..."
          git tag -a version-$NEW_VERSION -m version-$NEW_VERSION
          git push origin version-$NEW_VERSION

          gh pr create -B main -H "releases/version-$NEW_VERSION" --title "Make DataJunctino version $NEW_VERSION" --body "This is an automated PR triggered by the Weekly Version Bump action. Merging this PR will publish all the component for version $NEW_VERSION ."
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_SCOPED_TOKEN }}          